name: Deploy using image-release file

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read image name
        id: image
        run: |
          IMAGE=$(cat image-release.txt | tr -d '[:space:]')
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE="${{ steps.image.outputs.image }}"

            echo "Deploying $IMAGE"

            # pull image
            docker pull $IMAGE

            # stop old container
            docker stop nginx-rotate || true
            docker rm nginx-rotate || true

            # run new container
            docker run -d \
              --name nginx-rotate \
              -p 80:80 \
              $IMAGE